### PR TITLE
DRDT-70: Integrate Comscore

### PR DESCRIPTION
**Pull request by fariasf**

### CODE REVIEW

**Comment by fariasf** [comment]
Created new staging environment for pr-83. Here are some useful links:

[WordPress Admin](https://pr-83-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-83-drdt.pantheonsite.io/)
[Article](https://pr-83-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-83-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-83-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-83-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2773/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-83 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [92](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/pr-83/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [96](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/pr-83/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [96](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/pr-83/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [96](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/pr-83/page/lighthouse.report.html) | [92](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [90](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/pr-83/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2772/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Review by ChrisHursty — COMMENTED** [review]
This LGTM @fariasf but maybe @jrupan can verify too?

**Pull request merged**
