### PR TITLE
DRDT-88: Include php-ampqlib/php-amqplib dependency

### PR DESCRIPTION
**Pull request by fariasf**

### CODE REVIEW

**Comment by fariasf** [comment]
Created new staging environment for pr-77. Here are some useful links:

[WordPress Admin](https://pr-77-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-77-drdt.pantheonsite.io/)
[Article](https://pr-77-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-77-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-77-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-77-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2574/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-77 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [92](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/pr-77/homepage/lighthouse.report.html) | [95](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [97](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/pr-77/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [93](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/pr-77/listicle/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [94](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/pr-77/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/pr-77/hub/lighthouse.report.html) | [95](https://circleci.com/gh/fariasf/drdt-test/2575/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by santhoshmj** [comment]
@fariasf  Can you please resolve this conflict before i merge this to my branch

**Comment by santhoshmj** [comment]
@fariasf  Please resolve that conflicts, am not able to do it as i do not have write access.

**Comment by fariasf** [comment]
Updated staging environment for pr-77. Here are some useful links:

[WordPress Admin](https://pr-77-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-77-drdt.pantheonsite.io/)
[Article](https://pr-77-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-77-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-77-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-77-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2785/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
⚠ Frontend performance tests failed!

Full Lighthouse performance results:

| Page/Branch | pr-77 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [90](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/pr-77/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✘ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/pr-77/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [96](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/pr-77/listicle/lighthouse.report.html) | [91](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/pr-77/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/pr-77/hub/lighthouse.report.html) | [84](https://circleci.com/gh/fariasf/drdt-test/2786/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
@santhoshmj closing to get some more multidevs as in #75. Please re-open once unblocked, merge both branches together to get a single testing environment for this feature.

**Pull request closed without merging**
