### PR TITLE
[WIP] Add instant.page script for preloading

### PR DESCRIPTION
**Pull request by fariasf**
See https://instant.page/ - it uses `<link rel="prefetch">` to preload URLs on hover/touchstart.

### CODE REVIEW

**Comment by fariasf** [comment]
Created new staging environment for pr-69. Here are some useful links:

[WordPress Admin](https://pr-69-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-69-drdt.pantheonsite.io/)
[Article](https://pr-69-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-69-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-69-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-69-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2244/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-69 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [96](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/pr-69/homepage/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [96](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/pr-69/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [96](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/pr-69/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [97](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/pr-69/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/pr-69/hub/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2245/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-69. Here are some useful links:

[WordPress Admin](https://pr-69-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-69-drdt.pantheonsite.io/)
[Article](https://pr-69-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-69-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-69-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-69-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2253/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-69 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [95](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/pr-69/homepage/lighthouse.report.html) | [92](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [97](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/pr-69/article/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [97](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/pr-69/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [97](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/pr-69/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [96](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/pr-69/hub/lighthouse.report.html) | [92](https://circleci.com/gh/fariasf/drdt-test/2254/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-69. Here are some useful links:

[WordPress Admin](https://pr-69-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-69-drdt.pantheonsite.io/)
[Article](https://pr-69-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-69-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-69-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-69-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
Updated staging environment for pr-69. Here are some useful links:

[WordPress Admin](https://pr-69-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-69-drdt.pantheonsite.io/)
[Article](https://pr-69-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-69-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-69-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-69-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2266/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
⚠ Frontend performance tests failed!

Full Lighthouse performance results:

| Page/Branch | pr-69 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [89](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/pr-69/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✘ |
| Article | [97](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/pr-69/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [93](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/pr-69/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [97](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/pr-69/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [96](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/pr-69/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2267/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by subinviswanathan** [comment]
@fariasf lgtm apart from conflicts.

**Pull request closed without merging**
