### PR TITLE
check for css build on server

### PR DESCRIPTION
**Pull request by subinviswanathan**
This is just for testing purpose. dont merge it

### CODE REVIEW

**Comment by fariasf** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/fariasf/drdt-test/804/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Lighthouse test passed! The score of `60` isn't less than the acceptable score of `14` (`5` less than the score of `19` on the master branch)

View the full [Lighthouse performance report for `pull/28`](https://circleci.com/gh/fariasf/drdt-test/803/artifacts/0/artifacts/lighthouse_results/pr-28/lighthouse.report.html) and compare it to the [Lighthouse performance report for the `master` branch](https://circleci.com/gh/fariasf/drdt-test/803/artifacts/0/artifacts/lighthouse_results/master/lighthouse.report.html)

**Comment by fariasf** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/fariasf/drdt-test/810/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Lighthouse test failed! The score of `8` is than the acceptable score of `15` (`5` less than the score of `20` on the master branch)

View the full [Lighthouse performance report for `pull/28`](https://circleci.com/gh/fariasf/drdt-test/811/artifacts/0/artifacts/lighthouse_results/pr-28/lighthouse.report.html) and compare it to the [Lighthouse performance report for the `master` branch](https://circleci.com/gh/fariasf/drdt-test/811/artifacts/0/artifacts/lighthouse_results/master/lighthouse.report.html)

**Comment by subinviswanathan** [comment]
Closing this PR as it was just for testing

**Pull request closed without merging**
