### PR TITLE
Testing packages for Selenium and Headless Chrome browser.

### PR DESCRIPTION
**Pull request by BenoitRichard1212**
Added the automated installation of : 
Selenium
Chrome

Can be run from the local machine.

2 scripts handle installation and activation.

### CODE REVIEW

**Comment by fariasf** [comment]
Visual regression test failed! [Visual report](https://circleci.com/gh/fariasf/drdt-test/763/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Lighthouse test passed! The score of `66` isn't less than the acceptable score of `29` (`5` less than the score of `34` on the master branch)

View the full [Lighthouse performance report for `pull/25`](https://circleci.com/gh/fariasf/drdt-test/762/artifacts/0/artifacts/lighthouse_results/pr-25/lighthouse.report.html) and compare it to the [Lighthouse performance report for the `master` branch](https://circleci.com/gh/fariasf/drdt-test/762/artifacts/0/artifacts/lighthouse_results/master/lighthouse.report.html)

**Comment by fariasf** [comment]
@santhoshmj can you or someone on your team verify Behat tests? With Lando all tests work, even those that require JS. Please make sure they also work inside Vagrant.

**Comment by fariasf** [comment]
Updated staging environment for pr-25. Here are some useful links:

[WordPress Admin](https://pr-25-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-25-drdt.pantheonsite.io/)
[Article](https://pr-25-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-25-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-25-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-25-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
Updated staging environment for pr-25. Here are some useful links:

[WordPress Admin](https://pr-25-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-25-drdt.pantheonsite.io/)
[Article](https://pr-25-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-25-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-25-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-25-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
Updated staging environment for pr-25. Here are some useful links:

[WordPress Admin](https://pr-25-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-25-drdt.pantheonsite.io/)
[Article](https://pr-25-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-25-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-25-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-25-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/1642/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
⚠ Frontend performance tests failed!

Full Lighthouse performance results:

| Page/Branch | pr-25 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [65](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/pr-25/homepage/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✘ |
| Article | [97](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/pr-25/article/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [97](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/pr-25/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [95](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/pr-25/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [66](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/pr-25/hub/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/1641/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✘ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by BenoitRichard1212** [comment]
Added the fix for Windows environnement.

**Pull request merged**
