### PR TITLE
DRDT-53: Added dynamic code for newsletter in header, and scss

### PR DESCRIPTION
**Pull request by ChrisHursty**

### CODE REVIEW

**Comment by fariasf** [comment]
Created new staging environment for pr-73. Here are some useful links:

[WordPress Admin](https://pr-73-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-73-drdt.pantheonsite.io/)
[Article](https://pr-73-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-73-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-73-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-73-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2466/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
⚠ Frontend performance tests failed!

Full Lighthouse performance results:

| Page/Branch | pr-73 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [83](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/pr-73/homepage/lighthouse.report.html) | [92](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✘ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/pr-73/article/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [94](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/pr-73/listicle/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [97](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/pr-73/page/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [84](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/pr-73/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2467/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✘ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-73. Here are some useful links:

[WordPress Admin](https://pr-73-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-73-drdt.pantheonsite.io/)
[Article](https://pr-73-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-73-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-73-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-73-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2564/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-73 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [94](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/pr-73/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/pr-73/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/pr-73/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/pr-73/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/pr-73/hub/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2565/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-73. Here are some useful links:

[WordPress Admin](https://pr-73-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-73-drdt.pantheonsite.io/)
[Article](https://pr-73-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-73-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-73-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-73-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2621/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-73 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [92](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/pr-73/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [95](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/pr-73/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [97](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/pr-73/listicle/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/pr-73/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/pr-73/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2622/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by ChrisHursty** [comment]
Hey @fariasf when you get the chance, could you please review this PR and merge to Dev. This is all the work I "lost" when I had problems with my local. Thank you!

**Pull request merged**
