### PR TITLE
DRDT-71: Add official Facebook Pixel plugin

### PR DESCRIPTION
**Pull request by fariasf**

### CODE REVIEW

**Comment by fariasf** [comment]
Created new staging environment for pr-67. Here are some useful links:

[WordPress Admin](https://pr-67-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-67-drdt.pantheonsite.io/)
[Article](https://pr-67-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-67-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-67-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-67-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2204/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-67 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [91](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/pr-67/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/pr-67/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/pr-67/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/pr-67/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [98](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/pr-67/hub/lighthouse.report.html) | [95](https://circleci.com/gh/fariasf/drdt-test/2203/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-67. Here are some useful links:

[WordPress Admin](https://pr-67-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-67-drdt.pantheonsite.io/)
[Article](https://pr-67-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-67-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-67-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-67-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2210/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-67 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [96](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/pr-67/homepage/lighthouse.report.html) | [93](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/pr-67/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [94](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/pr-67/listicle/lighthouse.report.html) | [92](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/pr-67/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [98](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/pr-67/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2211/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by subinviswanathan** [comment]
@fariasf  See a conflict in composer.json

**Comment by fariasf** [comment]
Updated staging environment for pr-67. Here are some useful links:

[WordPress Admin](https://pr-67-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-67-drdt.pantheonsite.io/)
[Article](https://pr-67-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-67-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-67-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-67-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2327/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-67 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [96](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/pr-67/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [97](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/pr-67/article/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/pr-67/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/pr-67/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/pr-67/hub/lighthouse.report.html) | [94](https://circleci.com/gh/fariasf/drdt-test/2326/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Comment by fariasf** [comment]
Updated staging environment for pr-67. Here are some useful links:

[WordPress Admin](https://pr-67-drdt.pantheonsite.io/wp/wp-admin)

[Homepage](https://pr-67-drdt.pantheonsite.io/)
[Article](https://pr-67-drdt.pantheonsite.io/jobsite-tips/abandoned-cable-removal/)
[Listicle](https://pr-67-drdt.pantheonsite.io/jobsite-tips/exterior/12-scaffolding-safety-tips-and-handy-hints/)
[Page](https://pr-67-drdt.pantheonsite.io/about-construction-pro-tips/)
[Hub](https://pr-67-drdt.pantheonsite.io/jobsite-tips/)

**Comment by fariasf** [comment]
There are visual regressions! 

View the [full visual regression test report](https://circleci.com/gh/fariasf/drdt-test/2436/artifacts/0/artifacts/backstop_data/html_report/index.html)

**Comment by fariasf** [comment]
Congrats! Frontend performance tests passed!

Full Lighthouse performance results:

| Page/Branch | pr-67 | master | Result |
| --- | ---: | ---: | :---: |
| Homepage | [96](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/pr-67/homepage/lighthouse.report.html) | [96](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/master/homepage/lighthouse.report.html) | ✔ |
| Article | [98](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/pr-67/article/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/master/article/lighthouse.report.html) | ✔ |
| Listicle | [98](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/pr-67/listicle/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/master/listicle/lighthouse.report.html) | ✔ |
| Page | [98](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/pr-67/page/lighthouse.report.html) | [98](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/master/page/lighthouse.report.html) | ✔ |
| Hub | [97](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/pr-67/hub/lighthouse.report.html) | [97](https://circleci.com/gh/fariasf/drdt-test/2435/artifacts/0/artifacts/lighthouse_results/master/hub/lighthouse.report.html) | ✔ |


(**Note: Tests are against the _NOADS_ version of the pages!**)

**Pull request merged**
